// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAOvZGLM283idwSL3YmAt8MAFOT2Ur9rA',
    appId: '1:902180121403:web:9b3b2536e827a78b6f651e',
    messagingSenderId: '902180121403',
    projectId: 'task-management-app-e01f1',
    authDomain: 'task-management-app-e01f1.firebaseapp.com',
    storageBucket: 'task-management-app-e01f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcEmYI4IcTOHUGRr1jPzhxEzCR4-MobSY',
    appId: '1:902180121403:android:3adbfea62a05fe7f6f651e',
    messagingSenderId: '902180121403',
    projectId: 'task-management-app-e01f1',
    storageBucket: 'task-management-app-e01f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz1CQFoDpQAJyDWE4g3a2fI2t9TXz_v4g',
    appId: '1:902180121403:ios:09ad04c2677304176f651e',
    messagingSenderId: '902180121403',
    projectId: 'task-management-app-e01f1',
    storageBucket: 'task-management-app-e01f1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz1CQFoDpQAJyDWE4g3a2fI2t9TXz_v4g',
    appId: '1:902180121403:ios:bd4ca42d7a8f3c416f651e',
    messagingSenderId: '902180121403',
    projectId: 'task-management-app-e01f1',
    storageBucket: 'task-management-app-e01f1.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
